# Generated by Django 3.2.6 on 2021-08-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='appprovedDate',
            field=models.DateField(blank=True, null=True, verbose_name='The date and time the photo was approved'),
        ),
    ]
